### ISSUE TITLE
d3 time parser for .csv file

### ISSUE THREAD

**Issue by idakhiavi** [munroelab/cioos-dataviewer#4]
The .csv file taken from ERRDAP (e.g. https://www.smartatlantic.ca/erddap/tabledap/SMA_st_johns.html) has UTC timestamp and an extra line. The d3.timeparser does not seem to be working.

**Comment by jmunroe** [comment]
This seems to work.

https://stackoverflow.com/questions/17090642/d3-ignore-certain-row-in-csv/17091712#17091712
